name: Leiturando
description: "Um aplicativo para incentivar a leitura de livros."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  device_info: ^2.0.3
  device_info_plus: ^9.1.1
  dio: ^5.3.4
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.2
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  provider: ^6.1.1
  vocsy_epub_viewer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/leiturando_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/leiturando_logo.png"
    background_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/leiturando_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/leiturando_logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
